In [2]:
import pandas as pd
import numpy as np

# Questions

## Q1: Create a one-dimensional NumPy array of the numbers from 5 to 905, counting by 10?

In [ ]:
# np.arange(5, 905, 10)

q1_sol = __________

## Q2: Create the same NumPy array using a Python range and a list? (Hint: create a list)

In [ ]:
# np.array([i for i in range(5, 905, 10)])

q2_sol = _________

## Q3: How might you create a NumPy array of the capital letters, A-Z? (Hint: Ever heard of string.ascii_uppercase?)

In [ ]:
# np.array(list(ascii_uppercase))
# np.array([chr(i) for i in range(ord('A'), ord('Z') + 1)])

# array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
#       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'],
#      dtype='<U1')

q3_sol = ________

## Q4: Create a ten-element NumPy array object of all zeros and a six-element NumPy array object of all ones.

In [ ]:
# np.zeros(10)
# np.ones(6)

q4_sol_1 = __________
q4_sol_2 = __________

## Q5: Given an 2-D array, print the third column.

In [ ]:
input = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])

# print(input[:,2])

q5_sol = ___________

[33 66 99]


## Q6: Create an array of the shape (3, 4), filled with 64-bit integer zeros.

In [ ]:
# np.zeros(dtype=np.int64, shape=(3,4))

q6_sol = __________

## Q7: Split an array into 3 equal-sized sub-arrays.

In [ ]:
input = np.arange(7, 34, 1)
input = input.reshape(9,3)

# np.split(input, 3)

q7_sol = __________

[array([[ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]),
 array([[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33]])]

## Q8: Return the last 2 elements by each of the first rows of the (3,4) array. 

In [ ]:
input = np.arange(1,13,1)
input = input.reshape(3,4)
# input[:-1, -2:]

q8_sol = ________

array([[3, 4],
       [7, 8]])

## Q9: Return how many elements are greater than 5 in an array.

In [ ]:
input = np.arange(1,13,1)
input = input.reshape(3,4)

# (input>5).sum()

q9_sol = _______

## Q10: Delete the second column from an array and insert the following new column in the same place.

In [ ]:
input = np.array([[34,72,33],[82,22,32],[59,84,10]])
insert_data = np.array([[37,37,37]])

# sample = np.delete(input, 1, axis = 1) 
# sample = np.insert(sample , 1, insert_data, axis = 1)